#Update all the sections by editing the data.yml file inside _data folder.

baseurl: '/online-cv' #change it according to your repository name

# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: # blue turquoise green berry orange ceramic

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false