
title: My Resume
url: ''
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6




#Profile information
name: Kevin Vermeulen
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: kts.vermeulen@gmail.com
phone: 06 38172702
website: blog.webjeda.com #do not add http://
linkedin: alandoe
github: alandoe
twitter: '@twittername'
