#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic

# Tracker
analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false