# Site Settings
title: Hi Saya Dicka
url: '/online-cv'
baseurl: '/online-cv' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Muhammad Dicka Nirwansyah
tagline: Software Engineering
pic: dickanirwansyah.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: '<ul>
  <li>MI Al-anwar</li>
  <li>MTSN 19 Jakarta</li>
  <li>MAN 11 Jakarta</li>
  <li>Universitas Satya Negara Indonesia</li>
</ul>'

#sidebar links
email: dickanirwansyah@gmail.com
line: dickanirwansyah
website: dickanirwansyah.github.io/online-cv #do not add http://
linkedin: muhammad-dicka-nirwansyah-71a49b138
github: dickanirwansyah
twitter: '@dickanirwansyah'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
