# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: # blue turquoise green berry orange ceramic

# Profile information
name: Alan Doe
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Summarise your career here lorem ipsum dolor sit amet, consectetuer adipiscing elit.
You can <a href="#" target="_blank">download this free resume/CV template here</a>. Aenean
commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient
montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.'

# Sidebar links
email: hello@webjeda.com
phone: 012 345 6789
website: blog.webjeda.com #do not add http://
linkedin: alandoe
github: sharu725
twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
