services:
  jekyll:
    container_name: online-cv
    image: jekyll/builder:4.0
    command: jekyll serve --watch --force_polling --verbose --livereload --host 0.0.0.0
    volumes:
      - .:/srv/jekyll:Z
    environment:
      JEKYLL_UID: 1001
      JEKYLL_GID: 1001
      JEKYLL_VERSION: 3.8
    ports:
      - 4000:4000
